CREATE COLUMN TABLE STOCKALM ("OBJTYPE" NVARCHAR(20)  NOT NULL,
	"DOCNUM" INT  NOT NULL,
	 "LINENUM" INT NOT NULL,
	 "ITEMCODE" NVARCHAR(20)  NOT NULL,
	 "WHSCODE" NVARCHAR(8) ,
	 "STOCKALM" DECIMAL(21,6) ,
	 "STOCKTOT" DECIMAL(21,6) ,
	 PRIMARY KEY ("OBJTYPE","DOCNUM","LINENUM")) UNLOAD PRIORITY 5 AUTO MERGE 